### PR TITLE
osx-arm64 + linux-aarch64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/simbody - it would be great if you could have a look and merge. Thanks!

**Comment by moorepants** [comment]
This looks fine other than it may take hours to build the linux_aarch64 version. It's been running for 1 hour and 20 mins and the compilation is at 45%.

**Comment by Tobias-Fischer** [comment]
Thanks for having a look! Let's see whether it'll time out.

**Comment by Tobias-Fischer** [comment]
It took a while, but all good :)

**Comment by moorepants** [comment]
3hr 40 min!

**Pull request merged**
