### PR TITLE
Avoid to install vendored dirent.h and add cdt expat as dependency

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix https://github.com/conda-forge/simbody-feedstock/issues/39 .
Backport of https://github.com/simbody/simbody/pull/716 .

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Linux build is failing with:
~~~
[ 63%] Linking CXX executable ../../../simbody-visualizer
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libexpat.so.1, needed by /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so, not found (try using -rpath or -rpath-link)
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ErrorString'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_SetUserData'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetCurrentLineNumber'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ParserFree'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_SetElementHandler'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetCurrentColumnNumber'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetErrorCode'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetBuffer'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ParserCreate'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_Parse'
/home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ParseBuffer'
collect2: error: ld returned 1 exit status
make[2]: *** [simbody-visualizer] Error 1
make[1]: *** [Simbody/Visualizer/simbody-visualizer/CMakeFiles/simbody-visualizer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 63%] Linking CXX executable ../../TestCustomConstraints
[ 63%] Built target TestCustomConstraints
make: *** [all] Error 2
~~~

Probably this is not related to the specific change of the PR, but due to the re-rendering of the feedstock.

**Comment by traversaro** [comment]
> 
> 
> Linux build is failing with:
> 
> ```
> [ 63%] Linking CXX executable ../../../simbody-visualizer
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libexpat.so.1, needed by /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so, not found (try using -rpath or -rpath-link)
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ErrorString'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_SetUserData'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetCurrentLineNumber'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ParserFree'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_SetElementHandler'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetCurrentColumnNumber'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetErrorCode'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_GetBuffer'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ParserCreate'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_Parse'
> /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/simbody_1621256585314/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib/../lib/libGL.so: undefined reference to `XML_ParseBuffer'
> collect2: error: ld returned 1 exit status
> make[2]: *** [simbody-visualizer] Error 1
> make[1]: *** [Simbody/Visualizer/simbody-visualizer/CMakeFiles/simbody-visualizer.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 63%] Linking CXX executable ../../TestCustomConstraints
> [ 63%] Built target TestCustomConstraints
> make: *** [all] Error 2
> ```
> 
> Probably this is not related to the specific change of the PR, but due to the re-rendering of the feedstock.

Hopefully this will be fixed by https://github.com/conda-forge/simbody-feedstock/pull/40/commits/931483e1338f6dee0e1d7763f3721e358cf130ba .

**Comment by traversaro** [comment]
> Hopefully this will be fixed by 931483e .

The fix worked correctly.

**Comment by moorepants** [comment]
Are there any adverse consequences for removing this header? for example for packages that rely on it being there but don't have it installed via another method?

**Comment by traversaro** [comment]
> 
> 
> Are there any adverse consequences for removing this header? for example for packages that rely on it being there but don't have it installed via another method?

This is indeed a possibility. If you prefer, we can add [`dirent`](https://anaconda.org/conda-forge/dirent) as a run dependency on Windows, that should ensure that any downstream project that relies on `dirent.h`  being installed will continue to work.

**Comment by moorepants** [comment]
That sounds like the right thing to do.

**Comment by traversaro** [comment]
> 
> 
> That sounds like the right thing to do.

Yes, I was a bit hesitant as 

> 
> 
> That sounds like the right thing to do.

Done in https://github.com/conda-forge/simbody-feedstock/pull/40/commits/58cb6996180d81385195ebd86fc6fd2a948cdbec .

**Comment by moorepants** [comment]
LGTM. Thanks!

**Pull request merged**
