### PR TITLE
Rebuild with parallel OpenBLAS

### PR DESCRIPTION
**Pull request by jakirkham**
Bump build number and rebuild with the parallel OpenBLAS.

### CODE REVIEW

**Comment by moorepants** [comment]
How does changing that number do anything?

**Comment by jakirkham** [comment]
It creates a new package. The number itself isn't really changing something. It is that this will be linked to `libopenblasp` instead of `libopenblas`.

**Comment by ocefpaf** [comment]
> How does changing that number do anything?

@moorepants sadly every change in `numpy` linkages will need a rebuild of everything that links to it. Unfortunately we are not yet ready with an automatic re-build process for that and people are still merging at the bottom forcing us to do that manually. (Ping @pelson as we discussed this back in 2015! And this came back in the first `openblas` incident. Now we are in our second :unamused:)

Every extension that links to `numpy ` now needs to be re-build :sob:

**Comment by moorepants** [comment]
Ok, so this is just about forcing a rebuild to match with the latest openblas build.

**Comment by jakirkham** [comment]
Correct.

**Comment by jakirkham** [comment]
Weird we have no Travis CI build. Closing and reopening to try and trigger it.

**Comment by jakirkham** [comment]
Good. That added Travis CI.

**Comment by jakirkham** [comment]
> Every extension that links to numpy now needs to be re-build 😭

I don't think so. Please see this [comment]( https://github.com/conda-forge/openblas-feedstock/pull/9#issuecomment-235345336 ). Let's please try to keep the general discussion in that thread so it will be easier to follow.

**Comment by jakirkham** [comment]
Seems this is passing. Please merge when you are ready, @moorepants.

**Pull request merged**
